version: '3.8'
services:
  auth-service:
    build: ./auth-service
    ports:
      - "3001:3001"
  user-service:
    build: ./user-service
    ports:
      - "3002:3002"
  product-service:
    build: ./product-service
    ports:
      - "3003:3003"
  order-service:
    build: ./order-service
    ports:
      - "3004:3004"
  notification-service:
    build: ./notification-service
    ports:
      - "3005:3005"
  gateway-service:
    build: ./gateway-service
    ports:
      - "3000:3000"

