apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-error
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp-error
  template:
    metadata:
      labels:
        app: webapp-error
    spec:
      containers:
        - name: webapp-error
          image: kennytoro/errormsg
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: error-service
spec:
  selector:
    app: webapp-error
  type: NodePort
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
