apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-wear
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp-wear
  template:
    metadata:
      labels:
        app: webapp-wear
    spec:
      containers:
        - name: webapp-wear
          image: kennytoro/clothesmsg
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: wear-service
spec:
  selector:
    app: webapp-wear
  type: NodePort
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
