apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-video
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp-video
  template:
    metadata:
      labels:
        app: webapp-video
    spec:
      containers:
        - name: webapp-video
          image: kennytoro/videomsg
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: video-service
spec:
  selector:
    app: webapp-video
  type: NodePort
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
