apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-webapp
spec:
  defaultBackend:
    service:
      name: error-service
      port:
        number: 8080
  rules:
  - http:
      paths:
      - backend:
          service:
            name: weather-svc
            port:
              number: 3000
        path: /weatherapp
        pathType: Prefix

      - backend:
          service:
            name: video-service
            port:
              number: 8080
        path: /video
        pathType: Prefix
        
      - backend:
          service:
            name: stop-watch-svc
            port:
              number: 3500
        path: /time
        pathType: Prefix
